### PR TITLE
feat: adds laravel network validation defaults

### PR DESCRIPTION
**Pull request by aaronannecchiarico**
Adds some of the commonly used network validation types

- https://laravel.com/docs/9.x/validation#rule-ip
- https://laravel.com/docs/9.x/validation#ipv4
- https://laravel.com/docs/9.x/validation#ipv6
- https://laravel.com/docs/9.x/validation#rule-mac

Submitting for https://hacktoberfest.com/participation/#pr-mr-details

### CODE REVIEW

**Comment by setnemo** [comment]
@aaronannecchiarico Thank you for contributing 👍🏻

**Comment by aaronannecchiarico** [comment]
@setnemo No problem! When you have a moment could you add the hacktoberfest-accepted label so this repo is picked up for events! Thanks!

**Comment by setnemo** [comment]
@aaronannecchiarico I added, please check your contribution via the hacktoberfest website, I suppose everything can be OK right now

**Comment by trolzen** [comment]
@setnemo I think? in order to count it should be `hacktoberfest-accepted`, not just `hacktoberfest`.

**Pull request merged**
